/**
 * Workshops — Confluence 3.0
 *
 * Workshop shape:
 *   { id, title, resourcePerson, time, venue, block, registrationLink }
 */

const workshops = [
  {
    id: "design-and-control-of-motor-drives",
    title: "Design and Control of Motor Drives for Autonomous Vehicles – A Live Hardware Demonstration",
    resourcePerson: "Dr. Tony George, Tolarix Innovations Private Limited, Ernakulam",
    image: "/WorkshopSpeakers/workshop_01_Dr_Tony_George.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Power Electronics Lab, KE Block, 2nd Floor",
    block: "KE Block",
    registrationLink: "https://konfhub.com/workshop1",
    soldOut: true,
  },
  {
    id: "lighting-design-using-dialux-evo",
    title: "Lighting Design Using DIALux evo",
    resourcePerson: "Mr. Arun Joy, Electrical System Designer, Tritech Academy",
    image: "/WorkshopSpeakers/workshop_02_Arun_Joy.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Simulation Lab (EEE), KE Block, 2nd Floor",
    block: "KE Block",
    registrationLink: "https://konfhub.com/lighting-design-using-dialux-evo",
    soldOut: true,
  },
  {
    id: "advanced-modeling-using-revit-architecture",
    title: "Advanced Modeling Using Revit Architecture",
    resourcePerson: "Mr. Harikrishnan S, BIM Engineer, BIM Cafe Learning Hub",
    image: "/WorkshopSpeakers/workshop_03_Harikrishnan_S.jpg",
    time: "2:00 PM to 4:00 PM",
    venue: "CAD Lab (CE), KE Block, 1st Floor",
    block: "KE Block",
    registrationLink: "https://konfhub.com/advanced-modeling-using-revit-architecture",
    soldOut: true,
  },
  {
    id: "project-coordination-and-clash-detection-using-navisworks",
    title: "Project Coordination and Clash Detection Using Navisworks",
    resourcePerson: "Ananth Narayanan P, BIM Manager, Tritech Engineering",
    image: "/WorkshopSpeakers/workshop_04_Ananth_Narayanan_P.jpg",
    time: "2:00 PM to 4:00 PM",
    venue: "LH 22, KE Block, Fourth Floor",
    block: "KE Block",
    registrationLink: "https://konfhub.com/project-coordination-and-clash-detection-using-navisworks",
    soldOut: true,
  },
  {
    id: "ndt-in-welding-workshop",
    title: "NDT in Welding Workshop",
    resourcePerson: "Mr. Zakir Hussain B S, Tubazionic Engg. Pvt. Ltd.",
    image: "/WorkshopSpeakers/workshop_05_Zakir_Hussain_BS.jpg",
    time: "2:00 PM to 4:00 PM",
    venue: "CAD Lab (ME), KE Block, 1st Floor",
    block: "KE Block",
    registrationLink: "https://konfhub.com/ndt-in-welding-workshop",
    soldOut: true,
  },
  {
    id: "delta-plc-hmi-trainer-kit-automation-workshop",
    title: "Delta PLC & HMI Trainer Kit (Automation Workshop)",
    resourcePerson: "Sandeep Suresh, Project Engineer, IPCS Global",
    image: "/WorkshopSpeakers/workshop_06_Sandeep_Suresh.jpg",
    time: "2:00 PM to 4:00 PM",
    venue: "Measurements Lab, KE Block, 1st Floor",
    block: "KE Block",
    registrationLink: "https://konfhub.com/delta-plc-hmi-trainer-kit-automation-workshop",
    soldOut: true,
  },
  {
    id: "build-ship-an-ai-product",
    title: "Build & Ship an AI Product: Hands on Workshop",
    resourcePerson: "Mr. Sunith V S, Senior Software Engineer, LateLogic",
    image: "/WorkshopSpeakers/workshop_07_Sunith_VS.jpg",
    time: "2:00 PM to 4:00 PM",
    venue: "Lecture Auditorium 1, KE Block, Steag Extension, 4th Floor",
    block: "Steag Extension, KE Block",
    registrationLink: "https://konfhub.com/build-ship-an-ai-product-hands-on-worshop",
    soldOut: true,
  },
  {
    id: "from-code-to-app",
    title: "From Code to App: A Mobile Development Workshop",
    resourcePerson: "Mr. Vineeth Chandran, Senior Mobile Developer, Toobler",
    image: "/WorkshopSpeakers/workshop_08_Vineeth_Chandran.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Sycamore Lab – Phase I, KE Block, 3rd Floor",
    block: "KE Block",
    registrationLink: "https://konfhub.com/from-code-to-app-a-mobile-development-workshop",
    soldOut: true,
  },
  {
    id: "essential-project-management-methodologies",
    title: "Essential Project Management Methodologies",
    resourcePerson: "Mr. Adarsh Nair, Senior Delivery Manager, Adesso India Pvt. Ltd.",
    image: "/WorkshopSpeakers/workshop_09_Adarsh_Nair.jpg",
    time: "2:00 PM to 4:00 PM",
    venue: "Lecture Auditorium 2, KE Block, Steag Extension, 4th Floor",
    block: "Steag Extension, KE Block",
    registrationLink: "https://konfhub.com/essential-project-management-methodologies",
    soldOut: true,
  },
  {
    id: "hands-on-with-agentic-ai",
    title: "Hands-on with Agentic AI: Building Intelligent AI Using LLM Technology",
    resourcePerson: "Dr. Anil Raj, AI Consultant",
    image: "/WorkshopSpeakers/workshop_10_Dr_Anil_Raj.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Sycamore Lab – Phase II, KE Block, 3rd Floor",
    block: "KE Block",
    registrationLink: "https://konfhub.com/hands-on-with-agentic-ai-building-intelligent-ai-using-llm-technology",
    soldOut: true,
  },
  {
    id: "workshop-on-classification-of-stars",
    title: "Workshop on Classification of Stars",
    resourcePerson: "Dr. Joe Jacob and Sudheesh T P",
    image: "/WorkshopSpeakers/workshop_11_Dr_Joe_Jacob.jpg",
    image2: "/WorkshopSpeakers/workshop_11_Sudheesh_TP.jpg",
    time: "2:00 PM to 4:00 PM",
    venue: "Signal Processing Lab, Main Block, 2nd Floor",
    block: "Main Block",
    registrationLink: "https://konfhub.com/workshop-on-classification-of-stars",
    soldOut: true,
  },
  {
    id: "connect-to-remote-agents-with-adk",
    title: "Connect to Remote Agents with ADK and the Agent2Agent (A2A) SDK",
    resourcePerson: "Ajoe Joseph, Google Developer Expert – Cloud AI",
    image: "/WorkshopSpeakers/workshop_12_Ajoe_Joseph.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Shannon Lab, PG Block, 2nd Floor",
    block: "PG Block",
    registrationLink: "https://konfhub.com/connect-to-remote-agents-with-adk-and-the-agent2agent-a2a-sdk",
    soldOut: true,
  },
  {
    id: "linear-algebra-using-matlab",
    title: "Linear Algebra Using MATLAB",
    resourcePerson: "Dr. P R Neethu and Nella Jeena Jacob",
    image: "/WorkshopSpeakers/workshop_13_Dr_PR_Neethu_photo.png",
    image2: "/WorkshopSpeakers/workshop_13_Nella_Jeena_Jacob.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Zuse Lab, Main Block, 1st Floor",
    block: "Main Block",
    registrationLink: "https://konfhub.com/linear-algebra-using-matlab",
    soldOut: true,
  },
  {
    id: "innovation-entrepreneurship-and-startup-ecosystem",
    title: "Innovation, Entrepreneurship and Startup Ecosystem",
    image: null,
    // Note: Multiple speakers, no single photo available in the PDF
    resourcePersons: [
      { name: "Dr. J T Verghese", designation: "Director, Steag Energy Services" },
      { name: "Dr. Arun Kumar V", designation: "Addl. General Manager – R&D and Renewables, Steag" },
      { name: "Daniel Jeevan", designation: "Operations Head, Steag Centre for Smart City Technologies" },
      { name: "Jofin Joseph", designation: "Co-founder, Needletail AI" },
      { name: "Nasif NM", designation: "Head of Programs & Communication, Kerala Startup Mission" },
    ],
    time: "2:00 PM to 4:00 PM",
    venue: "Steag Centre, KE Block, Steag Extension, 2nd Floor",
    block: "Steag Extension, KE Block",
    registrationLink: "https://konfhub.com/innovation-entrepreneurship-and-startup-ecosystem",
    soldOut: true,
  },
  {
    id: "mobile-application-using-flutter",
    title: "Mobile Application Using Flutter",
    resourcePerson: "Poornesh P R, Senior Mobile Application Developer, Airpay Technologies Limited",
    image: "/WorkshopSpeakers/workshop_15_Poornesh_PR.png",
    time: "2:00 PM to 4:00 PM",
    venue: "CODD Lab, PG Block, 2nd Floor",
    block: "PG Block",
    registrationLink: "https://konfhub.com/mobile-application-using-flutter",
    soldOut: true,
  },
  {
    id: "sunya-labs-masterclass",
    title: "Sunya Labs MasterClass: Behind the LLM – The Core Computer Science Powers AI",
    resourcePerson: "Dr. M Sasikumar, Former Executive Director CDAC, Mumbai & Adjunct Professor, RSET",
    image: "/WorkshopSpeakers/workshop_16_Dr_M_Sasikumar.jpg",
    time: "2:00 PM to 4:00 PM",
    venue: "Turing Lab, PG Block, 2nd Floor",
    block: "PG Block",
    registrationLink: "https://konfhub.com/sunya-labs-masterclass-behind-the-llm-the-core-computer-science-powers-ai",
    soldOut: true,
  },
  {
    id: "agentic-ai-langgraph-lanchain-and-deepagents",
    title: 'Hands on Workshop on "Agentic AI: LangGraph, LanChain and DeepAgents"',
    resourcePerson: "Aditya Patil, Software Engineer (Agentic AI Developer) @IBM",
    image: "/WorkshopSpeakers/workshop_17_Aditya_Patil.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Quantum Lab, Main Block, 1st Floor",
    block: "Main Block",
    registrationLink: "https://konfhub.com/agentic-ai-langgraph-lanchain-and-deepagents",
    soldOut: true,
  },
  {
    id: "success-360-workshop",
    title: "Success 360 – Workshop on Career Readiness and Future Skills Including Design Thinking",
    resourcePerson: "Rajeev Srinivas, Region Head (Academic Alliances Group, Kerala), TCS",
    image: "/WorkshopSpeakers/workshop_18_Rajeev_Srinivas.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Dept. Library, ECE, Main Block, 2nd Floor",
    block: "Main Block",
    registrationLink: "https://konfhub.com/success-360-workshop-on-career-readiness-and-future-skills-including-design-thinking",
    soldOut: true,
  },
  {
    id: "modern-software-development-with-ai-copilots-agents",
    title: "Workshop on Modern Software Development with AI Copilots & Agents",
    resourcePerson: "Dr. Ajai Chemmanam, AI Architect, Abilytics Inc.",
    image: "/WorkshopSpeakers/workshop_19_Dr_Ajai_Chemmanam.jpg",
    time: "2:00 PM to 4:00 PM",
    venue: "Ulysses Lab, Main Block, 1st Floor",
    block: "Main Block",
    registrationLink: "https://konfhub.com/workshop-on-modern-software-development-with-ai-copilots-agents",
    soldOut: true,
  },
  {
    id: "from-chatbots-to-ai-agents",
    title: "From Chatbots to AI Agents: How Agentic AI Actually Works",
    resourcePerson: "Mr. Amal Babu, AI Lead, 10xDS",
    image: "/WorkshopSpeakers/workshop_20_Amal_Babu.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Photon Lab, Main Block, 1st Floor",
    block: "Main Block",
    registrationLink: "https://konfhub.com/from-chatbots-to-ai-agents-how-agentic-ai-actually-works",
    soldOut: true,
  },
  {
    id: "implementation-of-industry-4-0",
    title: "Implementation of Industry 4.0 at SFO Technology",
    resourcePerson: "Anil Raj, General Manager – Process and Equipment Engineering Head, NeST Group & SFO Technologies",
    image: "/WorkshopSpeakers/workshop_21_Anil_Raj.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Heisenberg Lab, Main Block, 1st Floor",
    block: "Main Block",
    registrationLink: "https://konfhub.com/implementation-of-industry-40-at-sfo-technology",
    soldOut: true,
  },
  {
    id: "from-ai-to-impact",
    title: "From AI to Impact: Practical AI & Data Transformation in Manufacturing",
    resourcePerson: "Prince Joseph, Group Chief Information Officer, NeST Group & SFO Technologies",
    image: "/WorkshopSpeakers/workshop_22_Prince_Joseph_fixed.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Hercules Lab, Main Block, 1st Floor",
    block: "Main Block",
    registrationLink: "https://konfhub.com/from-ai-to-impact-practical-ai-data-transformation-in-manufacturing",
    soldOut: true,
  },
  {
    id: "ai-for-future-engineers",
    title: "AI for Future Engineers",
    resourcePerson: "Prabhul Anil Narayanan, Chief Operating Officer, d'Katia Software Technologies Pvt. Ltd.",
    image: "/WorkshopSpeakers/workshop_23_option1.jpg",
    time: "2:00 PM to 4:00 PM",
    venue: "LH1, KE Block, 2nd Floor",
    block: "KE Block",
    registrationLink: "https://konfhub.com/ai-for-future-engineers",
    soldOut: true,
  },
  {
    id: "cyber-security-from-an-ai-perspective",
    title: "Cyber Security from an AI Perspective",
    resourcePerson: "Vijay Nair, Chief Technology Officer, PanApps International Pvt Ltd",
    image: "/WorkshopSpeakers/workshop_24_Vijay_Nair.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Sunya Labs, Main Block, Ground Floor",
    block: "Main Block",
    registrationLink: "https://konfhub.com/cyber-security-from-an-ai-perspective",
    soldOut: true,
  },
  {
    id: "ai-agents-zero-to-one",
    title: "AI Agents: Zero to One",
    resourcePerson: "Alosh Denny, Senior AI Engineer, InTensors",
    image: "/WorkshopSpeakers/workshop_25_Alosh_Denny_fixed.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Feynman Lab, Main Block, 2nd Floor",
    block: "Main Block",
    registrationLink: "https://konfhub.com/ai-agentszero-to-one",
    soldOut: true,
  },
  {
    id: "32-bit-revolution-mastering-stm32",
    title: "32-Bit Revolution Mastering STM32",
    resourcePerson: "Silsa Shaji, Junior Project Engineer, IPCS Global",
    image: "/WorkshopSpeakers/workshop_26_Silsa_Shaji.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Signals and Systems Lab, Main Block, 2nd Floor",
    block: "Main Block",
    registrationLink: "https://konfhub.com/32-bit-revolution-mastering-stm32",
    soldOut: true,
  },
  {
    id: "ai-study-buddy",
    title: "AI in Action: Building Intelligent Student Solution – AI Study Buddy",
    resourcePerson: "Sujith K, Senior Project Manager, Cubet Techno Labs Pvt. Ltd.",
    image: "/WorkshopSpeakers/workshop_27_Sujith_K.jpg",
    time: "2:00 PM to 4:00 PM",
    venue: "KleinRock Lab, PG Block, 2nd Floor",
    block: "PG Block",
    registrationLink: "https://konfhub.com/ai-in-action-building-intelligent-student-solutionai-study-buddy",
    soldOut: true,
  },
  {
    id: "ai-placement-buddy",
    title: "AI in Action: Building Intelligent Student Solution – AI Placement Buddy",
    resourcePerson: "Jishnu Pillai, AI Product Manager, Cubet Techno Labs Pvt. Ltd.",
    image: "/WorkshopSpeakers/workshop_28_Jishnu_Pillai.jpg",
    time: "2:00 PM to 4:00 PM",
    venue: "Shockley Lab, PG Block, 2nd Floor",
    block: "PG Block",
    registrationLink: "https://konfhub.com/ai-in-action-building-intelligent-student-solutionai-placement-buddy",
    soldOut: true,
  },
  {
    id: "tech-horizons-industry-4-0",
    title: "Tech Horizons: Industry 4.0 Ecosystems & Drone Systems",
    resourcePerson: "Assim Hussein, Founder, Makemybot",
    image: "/WorkshopSpeakers/workshop_29_Assim_Hussein.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Virtual Instrumentation Lab, PG Block, 2nd Floor",
    block: "PG Block",
    registrationLink: "https://konfhub.com/tech-horizons-industry-40-ecosystems-drone-systems",
    soldOut: true,
  },
  {
    id: "communication-influence-and-leadership",
    title: "Can You Make People Listen? Workshop on Communication, Influence and Leadership in the Age of AI",
    resourcePerson: "Dr. Nimish Joseph, Professor of Practice, St. Stephen's College, University of Delhi",
    image: "/WorkshopSpeakers/workshop_30_Dr_Nimish_Joseph.jpg",
    time: "2:00 PM to 4:00 PM",
    venue: "LH 3, KE Block, Second Floor",
    block: "KE Block",
    registrationLink: "https://konfhub.com/can-you-make-people-listen-workshop-on-communication-influence-and-leadership-in-the-age-of-ai",
    soldOut: true,
  },
  {
    id: "build-with-agents",
    title: "Build with Agents: Creating Intelligent Applications with Agentic AI",
    resourcePerson: "Ajay Ganapathi, AI Solutions Lead, MiPhi",
    image: "/WorkshopSpeakers/workshop_31_Ajay_Ganapathi.png",
    time: "2:00 PM to 4:00 PM",
    venue: "MiPhi Lab, KE Block, Steag Extension, 3rd Floor",
    block: "Steag Extension, KE Block",
    registrationLink: "https://konfhub.com/build-with-agents-creating-intelligent-applications-with-agentic-ai",
    soldOut: true,
  },
  {
    id: "cybersecurity-in-action",
    title: "Cybersecurity in Action: Understanding Threats, Attacks & Defense",
    resourcePerson: "Smrithi T, IT Engineer – Cybersecurity, IPCS Global",
    image: "/WorkshopSpeakers/workshop_32_Smrithi_T.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Dept Library (AE), KE Block, 2nd Floor",
    block: "KE Block",
    registrationLink: "https://konfhub.com/cybersecurity-in-action-understanding-threats-attacks-defense",
    soldOut: true,
  },
  {
    id: "dredging-desiltation",
    title: "Dredging & Desiltation: Modern Dredgers and Their Role in Disaster Prevention",
    resourcePerson: "Seby Toms, Executive Director, Dredging and Mining, Sooryavanshi Developers Pvt. Ltd.",
    image: "/WorkshopSpeakers/workshop_33_Sebastian.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Multimedia Hall, Main Block, Ground Floor",
    block: "Main Block",
    registrationLink: "https://konfhub.com/dredging-desiltation-modern-dredgers-and-their-role-in-disaster-prevention",
  },
  {
    id: "fire-safety-cpr-ppe",
    title: "Building a Safer Future: Practical Training in Fire Safety, CPR, PPE and Emergency Response",
    resourcePerson: "Chacko Varghese, Faculty Fire & Safety, Al Salama School of Safety Studies",
    image: "/WorkshopSpeakers/workshop_34_Chacko_Varghese.jpg",
    time: "2:00 PM to 4:00 PM",
    venue: "Survey Lab, KE Block, Ground Floor",
    block: "KE Block",
    registrationLink: "https://konfhub.com/building-a-safer-future-practical-training-in-fire-safety-cpr-ppe-and-emergency-response",
    soldOut: true,
  },
  {
    id: "ethical-tech-lab-workshop",
    title: "The Ethical Tech Lab Workshop",
    resourcePerson: "Sobhana Jaya Madhavan, Founder and CEO, MuchMagic Global",
    image: "/WorkshopSpeakers/workshop_35_Sobhana_Jaya_Madhavan.png",
    time: "2:00 PM to 4:00 PM",
    venue: "LH 5, KE Block, Second Floor",
    block: "KE Block",
    registrationLink: "https://konfhub.com/the-ethical-tech-lab-workshop",
    soldOut: true,
  },
  {
    id: "money-talks-building-wealth",
    title: "Money Talks: Building Wealth & Financial Freedom",
    resourcePerson: "Nikhil Gopalakrishnan, CEO, Pentad Securities",
    image: "/WorkshopSpeakers/workshop_36_Nikhil_Gopalakrishnan_photo.png",
    time: "2:00 PM to 4:00 PM",
    venue: "Gallery Hall, PG Block, Ground Floor",
    block: "PG Block",
    registrationLink: "https://konfhub.com/copy-money-talks-building-wealth-financial-freedom2",
  },
  {
    id: "ai-unplugged",
    title: "AI Unplugged: Inside the World of Artificial Intelligence",
    resourcePerson: "Jestin Wilson, Senior Architect, Saasvaap Inc.",
    image: "/WorkshopSpeakers/workshop_37_Jestin_Wilson.jpg",
    time: "2:00 PM to 4:00 PM",
    venue: "LH 6, KE Block, Second Floor",
    block: "KE Block",
    registrationLink: "https://konfhub.com/ai-unpluggedinside-the-world-of-artificial-intelligence",
    soldOut: true,
  },
];

export const POST_EVENT_WORKSHOPS = [
  {
    id: "umbraco-fundamentals-training",
    title: "Umbraco Fundamentals Training & Certification Program",
    image: "/WorkshopSpeakers/post_event_speaker2_final.jpg",
    image2: "/WorkshopSpeakers/post_event_speaker3_final.jpg",
    resourcePersons: [
      { name: "Muhammad Ansar", designation: "Co-founder & CTO, PHASES" },
      { name: "Dhanesh Kumar", designation: "Solutions Architect & Umbraco MVP, PHASES" },
      { name: "Farshadudheen K", designation: "Senior Software Engineer, PHASES" },
    ],
    date: "3 Sep 2026",
    time: "09:00 AM to 04:00 PM",
    venue: "Sycamore Lab (Phase 1), Third Floor, KE Block RSET",
    block: "KE Block",
    soldOut: true,
  },
];

export default workshops;
